# Config file for [Air](https://github.com/air-verse/air) in TOML format

root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
  pre_cmd = ["make gen-docs"]
  # cmd = "go build -o ./bin/main ./cmd/api"
  cmd = "go build -o ./bin/main ./cmd/main.go"
  post_cmd = []
  bin = "./bin/main"
  full_bin = ""
  args_bin = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "bin", "vendor", "testdata", "web", "docs", "scripts"]
  include_dir = []
  include_file = []
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = true
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  main_only = false
  time = false
  silent = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

# [proxy]
# # Enable live-reloading on the browser.
# enabled = true
# proxy_port = 8090
# app_port = 8080