services:
  db:
    image: postgres:17.0-alpine3.20
    container_name: invest-postgres-db
    environment:
      POSTGRES_DB: invest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5440:5432"

volumes:
  db-data:
